config/routes.rb
Rails.application.routes.draw do

  root to:  'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  get 'sign_in', to: 'static_pages#new', as: :sign_in
  post 'sign_in', to: 'static_pages#create'


  get 'sign_up', to: 'user#new', as: :sign_up
  post 'sign_up', to: 'user#create'

  delete 'log_out', to: 'user#destroy', as: :log_out

  get 'active_account/:token' => 'user#active_account', as: :active_account

  resources :microposts
  resources :comments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :micropost

  default_scope -> { order(created_at: :desc) }

  validates :content, presence: true, length: { maximum: 140 }
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  has_many :comments
  
  default_scope -> { order(created_at: :desc) }

  validates :content, presence: true, length: { maximum: 140 }

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :microposts, dependent: :destroy
  has_many :comments
  
  before_create :generate_activation_token
  before_save { self.email.downcase! }

  attr_accessor :activation_token
  attr_accessor :remember_token
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :name, presence: true, on: create
  validates :email, uniqueness: true, format: { with: VALID_EMAIL_REGEX, message: 'value is invalid'}

  def authenticated?(attr, token)
    digest = self.send("#{attr}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def active_account
    self.update_attributes activated: true, activated_at: Time.now, activation_digest: nil
  end

  def remember
    self.remember_token  = SecureRandom.urlsafe_base64
    self.update_attribute(:remember_digest, BCrypt::Password.create(self.remember_token))
  end

  def forget
    self.update_attribute(:remember_digest, nil)
  end

  private

  def generate_activation_token
    self.activation_token = SecureRandom.urlsafe_base64
    self.activation_digest = BCrypt::Password.create(self.activation_token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @comment = Comment.new
  end

  def create
    @comment = current_user.comments.build(comment_params)
    if @comment.save
      flash[:success] = 'You are comment successfully'
      redirect_to @comment.micropost
      #redirect_back(fallback_location: root_path)
    else
      @post = @comment.micropost
      flash.now[:warning] = 'Errors'
      render 'microposts/show'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :micropost_id)
  end

end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  def index
    @posts = Micropost.paginate(page: params[:page], per_page: 10)
  end

  def show
    @post = Micropost.find_by id: params[:id]
    @comment = Comment.new
  end

  def new
    @post = Micropost.new
  end

  def edit
    @post = Micropost.find(params[:id])
  end

  def update
    @post = Micropost.find(params[:id])
    if @post.update_attributes(micropost_params)
      flash[:success] = 'Edit post successfully'
      redirect_to root_path
    else
      flash[:warning] = 'Errors'
      render :edit
    end
  end

  def create
    @post = current_user.microposts.build(micropost_params)

    if @post.save
      flash[:success] = "Micropost created!"
      redirect_to root_path
    else
      flash.now[:warning] = 'Input again'
      render :new
    end
  end

  def destroy
    @post = current_user.microposts.find_by(id: params[:id])
    if @post.destroy
      flash[:success] = "Micropost deleted"
    else
      flash[:alert] = 'Errors'
    end
    redirect_to root_path
  end

  private

  def micropost_params
    params.require(:micropost).permit(:content)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def new
    if session[:user_id]
      flash[:success] = 'You have already sign in'
      redirect_to root_path
    else
      @user = User.new
    end
  end

  def create
    @user = User.find_by email: params[:user][:email]
      if @user&.authenticate(params[:user][:password])
        if @user.activated?
          log_in(@user)
          params[:user][:remember_me] == '1' ? remember(@user) : forget(@user)
          flash[:success] = 'You sign in successfully'
          redirect_to root_path
        else
          flash.now[:warning] = 'Your account is not activated. Plase active it first and sign in again'
          render :new
        end
      else
        @user = User.new user_params
        flash.now[:danger] = 'Can not found with this email'
        render :new
      end
  end

  private

  def user_params
    params.require(:user).permit :email, :password
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    if @user.save
      UsersMailer.confirm_email(@user).deliver_now
      flash[:success] = 'You sign up successfully'
      redirect_to root_path
    else
      flash.now[:warning] = 'Input again'
      render :new
    end
  end

  def destroy
    log_out(@user)
    flash[:success] = 'You are log out successfully'
    redirect_to root_path
  end

  def active_account
    @user = User.find_by email: params[:email]

    if @user&.authenticated?(:activation, params[:token]) && @user&.active_account
      flash[:success]  =  'You are activated successfully'
    else
      flash[:warning] = 'Active link is valid'
    end
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def log_out user
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user&.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/comments/index.html.erb
<%= form_for @comment do |f| %>
<div class="form-group">
  <%= f.label :content %>
  <%= f.text_area :content, class: 'form-control', placeholder: 'Write your comment' %>
</div>

<%= f.submit 'Comment', class: 'btn btn-outline-secondary' %>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |key, message| %>
  <div class="alert alert-<%= key %> alert-dismissible fade show" role="alert">
    <%= message %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="container">
  <p>© Company 2017-2018</p>
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="/">Blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav ml-auto">
      <%if current_user.present?%>
      <li >
        <%= link_to 'New Post', new_micropost_path, class: 'nav-link' %>
      </li>
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.name %>
          </button>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="#">Profile</a>
            <%= link_to 'Log out', log_out_path, class: 'dropdown-item', method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        </div>
      <%else%>
        <li >
          <%= link_to 'Sign in', sign_in_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', sign_up_path, class: 'nav-link' %>
        </li>
      <%end%>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogger</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <main role='main'>
      <%= render 'layouts/flash' %>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/microposts/edit.html.erb
<div class='row justify-content-center align-items-center h-100'>
  <div class='col col-sm-6 col-md-6 col-lg-4 col-xl-3'>
    <center> <h1><small> CREATE NEW POST </small> </h1> </center>
    <%= form_for @post do |f| %>
      <div class="form-group">
        <%= f.label :content %>
        <%= f.text_area :content, class: 'form-control', placeholder: "Compose new micropost..." %>
      </div>
      <center><%= f.submit 'Edit Post', class: 'btn btn-primary' %></center>
    <% end %>
  </div>
</div>

app/views/microposts/index.html.erb
<% @posts.each do |post| %>
  <div class="media">
    <div class="media-left">
      <img src="https://www.w3schools.com/bootstrap/img_avatar3.png" class="media-object" style="width:45px">
    </div>
    <div class="media-body">
      <h4 class="media-heading"><%= post.user.name %>
        <small>
          <i>Posted on
            <%= post.created_at %></i>
        </small>
      </h4>
      <p><%= link_to post.content, micropost_path(post) %></p>
      <button><%= link_to 'Edit', edit_micropost_path(post), class: 'btn btn-outline-secondary', type: 'button' %></button>
      <button><%= link_to 'Delete', micropost_path(post), class: 'btn btn-outline-primary', type: 'button', method: :delete, data: { confirm: 'Are you sure?' } %></button>
    </div>
  </div>
<% end %>

<%= will_paginate @posts %>

app/views/microposts/new.html.erb
<div class='row justify-content-center align-items-center h-100'>
  <div class='col col-sm-6 col-md-6 col-lg-4 col-xl-3'>
    <center> <h1><small> CREATE NEW POST </small> </h1> </center>
    <%= form_for @post do |f| %>
      <div class="form-group">
        <%= f.label :content %>
        <%= f.text_area :content, class: 'form-control', placeholder: "Compose new micropost..." %>
      </div>
      <center><%= f.submit 'Post', class: 'btn btn-primary' %></center>
    <% end %>
  </div>
</div>

app/views/microposts/show.html.erb
<div class="media">
  <div class="media-left">
    <img src="https://www.w3schools.com/bootstrap/img_avatar3.png" class="media-object" style="width:45px">
  </div>
  <div class="media-body">
    <h4 class="media-heading"><%= @post.user.name %>
      <small>
        <i>Posted on
          <%= @post.created_at %></i>
      </small>
    </h4>
    <p><%= @post.content %></p>
  </div>
</div>

<%= form_for @comment do |f| %>
<div class="form-group">
  <%= f.text_field :micropost_id, :value => @post.id, type: 'hidden' %>
</div>

<div class="form-group">
  <%= f.label :content %>
  <%= f.text_area :content, class: 'form-control', placeholder: 'Write your comment' %>
</div>

<%= f.submit 'Comment', class: 'btn btn-outline-secondary' %>
<% end %>

<% @post.comments.each do |c| %>
  <div class="media">
    <div class="media-left">
      <img src="https://www.w3schools.com/bootstrap/img_avatar3.png" class="media-object" style="width:45px">
    </div>
    <div class="media-body">
      <h4 class="media-heading"><%= c.user.name %>
        <small> <i>Posted on <%= c.created_at %> </i> </small>
      </h4>
      <p><%= c.content %></p>
    </div>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<div class="jumbotron">
  <div class="container">
    <h1 class="display-3">Hello, world!</h1>
    <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
    <p>
      <%= link_to 'Show posts', microposts_path, class:"btn btn-primary btn-lg", role: "button" %>
    </p>
  </div>
</div>

app/views/static_pages/new.html.erb
<% provide(:title, "Log in") %>
  <center>
    <h1>Sign in</h1>
  </center>
  <div class='row justify-content-center align-items-center h-100'>
    <div class='col col-sm-6 col-md-6 col-lg-4 col-xl-3'>
      <%= form_for @user, url: '/sign_in' do |f| %>
      <div class="form-group">
        <%=f.label :email %>
        <%=f.text_field :email, class: 'form-control'%>
      </div>

      <div class="form-group">
        <%=f.label :password %>
        <%=f.password_field :password, class: 'form-control'%>
      </div>
      <%= label_tag :remember_me, class: "checkbox inline" do %>
        <%= check_box_tag :remember_me, '1', false, name: 'user[remember_me]' %>
        <span>Remember me on this computer</span>
    <%end%>
    <%= f.submit 'Log in', class: 'btn btn-primary' %>

  <%end%>
  <p>New user?
    <%= link_to "Sign up now!", sign_up_path %>
  </p>
</div>
</div>

app/views/user/new.html.erb
<div class='row justify-content-center align-items-center h-100'>
  <div class='col col-sm-6 col-md-6 col-lg-4 col-xl-3'>
    <center><h1>Sign up</h1></center>
    <%= form_for @user, url: '/sign_up' do |f| %>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %> </li>
        <%end%>
      </ul>
      <div class="form-group">
        <%=f.label :name %>
        <%=f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%=f.label :email %>
        <%=f.text_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%=f.label :password %>
        <%=f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%=f.label :password_confirmation %>
        <%=f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%=f.submit class:'btn btn-primary' %>
      <%= link_to 'Sign in', sign_in_path, class:'btn btn-secondary'%>
    <%end%>
  </div>
</div>